// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.sas.query.generation.representations;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.commons.rest.representations.Link;

public class CatalogBuilder extends CatalogBuilderBase<CatalogBuilder>
{
    public static CatalogBuilder catalog()
    {
        return new CatalogBuilder();
    }

    public CatalogBuilder() {
        super(new Catalog());
    }

    public Catalog build()
    {
        return getInstance();
    }
}

class CatalogBuilderBase<GeneratorT extends CatalogBuilderBase<GeneratorT>>
{
    private Catalog instance;

    protected CatalogBuilderBase(Catalog aInstance) {
        instance = aInstance;
    }

    protected Catalog getInstance()
    {
        return instance;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withCreationTimeStamp(Date aValue)
    {
        instance.setCreationTimeStamp(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withModifiedTimeStamp(Date aValue)
    {
        instance.setModifiedTimeStamp(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withCreatedBy(String aValue)
    {
        instance.setCreatedBy(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withModifiedBy(String aValue)
    {
        instance.setModifiedBy(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withContent(String aValue)
    {
        instance.setContent(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withId(String aValue)
    {
        instance.setId(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withName(String aValue)
    {
        instance.setName(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withDescription(String aValue)
    {
        instance.setDescription(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withLinks(List<Link> aValue)
    {
        instance.setLinks(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withAddedLink(Link aValue)
    {
        if (instance.getLinks() == null) {
            instance.setLinks(new ArrayList<Link>());
        }

        ((ArrayList<Link>) instance.getLinks()).add(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withVersion(int aValue)
    {
        instance.setVersion(aValue);

        return (GeneratorT) this;
    }
}
